# Generated by Django 6.0.3 on 2026-03-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_document_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
