# Generated by Django 6.0.3 on 2026-03-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR_Admin', 'HR_Admin'), ('Recruiter', 'Recruiter'), ('Interviewer', 'Interviewer')], max_length=20),
        ),
    ]
