# Generated by Django 6.0.3 on 2026-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'HR Admin'), ('recruiter', 'Recruiter'), ('interviewer', 'Interviewer')], max_length=20),
        ),
    ]
