# Generated by Django 6.0.3 on 2026-03-27 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('new_application', 'New Application'), ('stage_changed', 'Stage Changed'), ('interview_reminder', 'Interview Reminder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-is_read', '-created_at'], name='notificatio_recipie_39328c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_dd6756_idx'),
        ),
    ]
