# Generated by Django 6.0.3 on 2026-03-27 08:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0004_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('max_score', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location_or_link', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('Technical', 'Technical'), ('Behavioural', 'Behavioural'), ('HR', 'HR'), ('Final', 'Final')], max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.application')),
                ('interviewers', models.ManyToManyField(limit_choices_to={'role': 'interviewer'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_recommendation', models.CharField(choices=[('Hire', 'Hire'), ('No Hire', 'No Hire'), ('Maybe', 'Maybe')], max_length=10)),
                ('notes', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='interviews.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('interview', 'interviewer')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.feedbackrubric')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='interviews.interviewfeedback')),
            ],
        ),
    ]
